// src/components/EmailCopier.vue
<template>
  <div class="relative mx-auto flex w-fit flex-row items-center text-xl font-black text-accent">
    <p class="border-r-2 border-bg bg-highlight px-3 py-4 transition-colors">salevic@lu-ka.me</p>

    <button class="bg-highlight px-3 py-4 transition-colors hover:bg-zinc-700 active:bg-zinc-600" @click.prevent="copy">
      copy me
    </button>

    <p v-if="showCopyText" class="absolute -right-20 select-none text-base sm:-bottom-8 sm:right-5" aria-hidden="true">
      copied!
    </p>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

const showCopyText = ref(false);

async function copyText(): Promise<boolean> {
  const text = "salevic@lu-ka.me";

  try {
    await navigator.clipboard.writeText(text);

    return Promise.resolve(true);
  } catch (err) {
    console.error(err);

    return Promise.reject(false);
  }
}

const copy = async () => {
  copyText().then(() => {
    showCopyText.value = true;

    setTimeout(() => {
      showCopyText.value = false;
    }, 600);
  });
};
</script>

// src/components/EmailCopier.svelte
<script lang="ts">
  let showTooltip = $state(false);

  function toggleTooltip() {
    if (showTooltip) return;

    showTooltip = true;

    setTimeout(() => showTooltip = false, 1000);
  }

  async function copy() {
    const text = "salevic@lu-ka.me";

    try {
      await navigator.clipboard.writeText(text);

      toggleTooltip();

      return Promise.resolve(true);
    } catch (err) {
      console.error(err);

      return Promise.reject(false);
    }
  }
</script>

<div class="flex flex-row sm:flex-col items-stretch w-fit font-mono mt-4">
  <div class="flex">
    <p class="text-amber-500 text-2xl select-all bg-neutral-800 px-2 py-1 border-y-2 border-l-2">salevic@lu-ka.me</p>

    <div class="border-2 border-l-neutral-900">
      <button class="text-amber-500 h-full bg-neutral-800 hover:bg-neutral-900 px-2" onclick={copy}>copy me</button>
    </div>
  </div>

  {#if showTooltip}
    <p class="ml-3 my-auto sm:mt-2 sm:ml-0 font-black">copied!</p>
  {/if}
</div>
